<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */
declare(strict_types=1);

namespace MagedIn\ChatGpt\Api;

/**
 * ChatGPT Configuration Interface
 *
 * Defines the contract for ChatGPT configuration management
 */
interface ConfigInterface
{
    /**
     * Check if ChatGPT is enabled
     *
     * @param string|null $scopeType
     * @param string|int|null $scopeCode
     * @return bool
     */
    public function isEnabled(?string $scopeType = null, $scopeCode = null): bool;

    /**
     * Get decrypted API key
     *
     * @param string|null $scopeType
     * @param string|int|null $scopeCode
     * @return string|null
     */
    public function getApiKey(?string $scopeType = null, $scopeCode = null): ?string;

    /**
     * Get configured ChatGPT model
     *
     * @param string|null $scopeType
     * @param string|int|null $scopeCode
     * @return string
     */
    public function getModel(?string $scopeType = null, $scopeCode = null): string;

    /**
     * Get default maximum tokens
     *
     * @return int
     */
    public function getDefaultMaxTokens(): int;

    /**
     * Get default temperature
     *
     * @return float
     */
    public function getDefaultTemperature(): float;

    /**
     * Check if ChatGPT is properly configured
     *
     * @param string|null $scopeType
     * @param string|int|null $scopeCode
     * @return bool
     */
    public function isConfigured(?string $scopeType = null, $scopeCode = null): bool;

    /**
     * Get all configuration as array
     *
     * @param string|null $scopeType
     * @param string|int|null $scopeCode
     * @return array
     */
    public function getConfiguration(?string $scopeType = null, $scopeCode = null): array;
}